### ISSUE TITLE
Required System Tab Access

### ISSUE THREAD

**Issue by nhmathis** [UrbanCode/Send-SMTP-Email-UCD#4]
User reported that if they don't have privileges to UCD's **Server Configuration/Manage Security & Web UI/Settings Tab** then the mail cannot be sent.

Logs: 
``` 
Caught: java.io.IOException: 400 Bad Request
java.io.IOException: 400 Bad Request
   at com.urbancode.ud.client.UDRestClient.getSystemConfiguration(UDRestClient.java:2128)
   at com.urbancode.ud.client.UDRestClient$getSystemConfiguration.call(Unknown Source)
   at send_smtp_email.run(send_smtp_email.groovy:38)
```

Are these privileges necessary for the plugin to work? They also reported that this happened after the upgrade to UCD v6.2.4.2.

**Comment by nhmathis** [comment]
Short answer is yes. 

As of the current plug-in, the **System Settings** privileges are required for the plugin step to run. The line in question is here: https://github.com/IBM-UrbanCode/Send-SMTP-Email-UCD/blob/master/src/main/zip/send_smtp_email.groovy#L38

This method is used to quickly get around invalid SSL Certificate issues. If building locally, this line can simply be removed and recompiled without issues. However, you may receive a invalid SSL certificate error. This will require the management of import of the certificate in question onto your runtime agent. This is documented further in the Knowledge Center. 

Regardless, the **Mail Server Settings** will still need to be configured by someone with access to the **System Setting** tab. Once configured, any user should be able to access them.

Edit: This is only true if you leave the `SMTP Host`, `SMTP Port`, `SMTP Secure TLS`, and `Sender Email Address` properties blank. Specify these properties to skip the automated retrieval from the general settings page.

**Comment by nhmathis** [comment]
Future update should include a short checkbox feature flag around this line to use/ignore it when checked/unchecked.

**Comment by chris-ratcliffe** [comment]
@nhmathis , I tried rebuilding the plugin with that line commented out, however, I continued to get the same error: 

java.io.IOException: 400 
Error processing command: User lacks privilege: Settings Tab

The only way I could get around it was to explicitly set the SMTP Host, SMTP Port, SMTP Secure TLS, and Sender Email Addresses in the plugin step's property fields.  This ensures the section of code that attempts to query this information from the UCD Server doesn't get called.

**Comment by nhmathis** [comment]
That makes sense. If left blank, the plugin will try and retrieve the properties from the settings pages. You will need to specify the `SMTP Host`, `SMTP Port`, `SMTP Secure TLS`, and `Sender Email Address` properties to prevent this unauthorized retrieval.

**Comment by chris-ratcliffe** [comment]
Yes, this is what I have done, but creating a generic process wrapper that explicitly sets those values, and have my users use that instead of the plugin directly, or if they, they have to set them themselves.

**Comment by nhmathis** [comment]
Glad you were able to figure it out.

If any easier, I suggest looking to [environment/process/component properties](https://www.ibm.com/support/knowledgecenter/en/SS4GSP_6.1.2/com.ibm.udeploy.reference.doc/topics/ud_properties.html). You can redefine the same SMTP values in the process configuration and reference them that way. If everyone should be using one set of credentials, then this may be the easiest way.

**Comment by chris-ratcliffe** [comment]
Yes, we made use of System properties to store the values, and referenced from those.
